# Generated by Django 5.2.17 on 2026-08-26 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="responsible_employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Получат уведомление за месяц до окончания договора",
                related_name="responsible_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственные сотрудники",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["end_date"], name="contracts_c_end_dat_dedd36_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contract",
            unique_together={("account", "number")},
        ),
    ]
