# Generated by Django 5.2.17 on 2026-08-27 07:14

import apps.contracts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название шаблона"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.contracts.models.contract_template_upload_path,
                        verbose_name="Файл шаблона (.docx)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Используется при формировании договора. Активным должен быть только один.",
                        verbose_name="Активный шаблон",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
            ],
            options={
                "verbose_name": "Шаблон договора",
                "verbose_name_plural": "Шаблоны договора",
                "ordering": ("-is_active", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="GeneratedContractFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.contracts.models.generated_contract_upload_path,
                        verbose_name="PDF договора",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Сформирован"),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_file",
                        to="contracts.contract",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем сформирован",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сформированный договор (PDF)",
                "verbose_name_plural": "Сформированные договоры (PDF)",
            },
        ),
    ]
