# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер лицевого счёта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Открыт"), ("closed", "Закрыт")],
                        default="active",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "registered_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Используется для начислений по тарифу «руб/чел»",
                        verbose_name="Кол-во зарегистрированных лиц",
                    ),
                ),
                ("opened_at", models.DateField(verbose_name="Дата открытия")),
                (
                    "closed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата закрытия"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="addresses.unit",
                        verbose_name="Помещение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лицевой счёт",
                "verbose_name_plural": "Лицевые счета",
                "ordering": ("number",),
                "indexes": [
                    models.Index(
                        fields=["number"], name="accounts_pe_number_86a274_idx"
                    ),
                    models.Index(
                        fields=["status"], name="accounts_pe_status_de2778_idx"
                    ),
                ],
            },
        ),
    ]
