# Generated by Django 5.2.17 on 2026-08-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_personalaccount_registered_count"),
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalaccount",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Какие услуги из справочника начисляются на этот лицевой счёт",
                related_name="accounts",
                to="services.service",
                verbose_name="Услуги",
            ),
        ),
    ]
