# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Снимок ставки тарифа — не меняется при последующем изменении тарифа",
                        max_digits=12,
                        verbose_name="Ставка на момент начисления",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1"),
                        max_digits=12,
                        verbose_name="Объём (площадь/чел/потребление)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка начисления",
                "verbose_name_plural": "Строки начислений",
                "ordering": ("service__sort_order",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата оплаты")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Номер платежа/квитанции",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Внесён"),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплаты",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="Recalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.DateField(verbose_name="За какой период пересчитывается"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Положительная — доначисление, отрицательная — уменьшение",
                        max_digits=12,
                        verbose_name="Сумма корректировки",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("temporary_absence", "Временное отсутствие"),
                            ("poor_quality", "Некачественная услуга"),
                            ("tariff_change", "Изменение тарифа задним числом"),
                            ("meter_correction", "Корректировка показаний"),
                            ("manual", "Ручная корректировка"),
                            ("other", "Прочее"),
                        ],
                        max_length=20,
                        verbose_name="Причина",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Перерасчёт",
                "verbose_name_plural": "Перерасчёты",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        verbose_name="Расчётный период (первое число месяца)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("final", "Проведено")],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Входящее сальдо",
                    ),
                ),
                (
                    "accrued_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Начислено",
                    ),
                ),
                (
                    "recalculation_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Перерасчёт",
                    ),
                ),
                (
                    "paid_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Оплачено",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Исходящее сальдо",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Сформировано"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="accounts.personalaccount",
                        verbose_name="Лицевой счёт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Начисление",
                "verbose_name_plural": "Начисления",
                "ordering": ("-period", "account"),
            },
        ),
    ]
