# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("billing", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — сформировано автоматически",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сформировано пользователем",
            ),
        ),
        migrations.AddField(
            model_name="chargeline",
            name="charge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="billing.charge",
                verbose_name="Начисление",
            ),
        ),
        migrations.AddField(
            model_name="chargeline",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charge_lines",
                to="services.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddField(
            model_name="chargeline",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charge_lines",
                to="services.tariff",
                verbose_name="Тариф",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="accounts.personalaccount",
                verbose_name="Лицевой счёт",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="billing.charge",
                verbose_name="Отнесено на начисление",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем внесено",
            ),
        ),
        migrations.AddField(
            model_name="recalculation",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recalculations",
                to="accounts.personalaccount",
                verbose_name="Лицевой счёт",
            ),
        ),
        migrations.AddField(
            model_name="recalculation",
            name="applied_in_charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recalculations",
                to="billing.charge",
                verbose_name="Учтено в начислении",
            ),
        ),
        migrations.AddField(
            model_name="recalculation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем создан",
            ),
        ),
        migrations.AddField(
            model_name="recalculation",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recalculations",
                to="services.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(
                fields=["account", "period"], name="billing_cha_account_ed42b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="charge",
            index=models.Index(fields=["period"], name="billing_cha_period_030708_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="charge",
            unique_together={("account", "period")},
        ),
        migrations.AlterUniqueTogether(
            name="chargeline",
            unique_together={("charge", "service")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["account", "date"], name="billing_pay_account_19a90b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recalculation",
            index=models.Index(
                fields=["account", "period"], name="billing_rec_account_a35a0e_idx"
            ),
        ),
    ]
