# Generated by Django 5.2.17 on 2026-08-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charge",
            name="recalculation_total",
        ),
        migrations.DeleteModel(
            name="Recalculation",
        ),
    ]
