# Generated by Django 5.2.17 on 2026-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Код услуги")),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("per_area", "руб/м² (площадь)"),
                            ("per_person", "руб/чел (зарегистрированные лица)"),
                            ("fixed", "фиксированная сумма на лицевой счёт"),
                            (
                                "per_consumption",
                                "руб/куб.м, руб/кВт·ч (по показаниям приборов учёта)",
                            ),
                        ],
                        max_length=20,
                        verbose_name="Способ расчёта",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        blank=True,
                        help_text="м², чел., м³, кВт·ч — для отображения в квитанции",
                        max_length=20,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок в квитанции"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Справочник услуг",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Значение зависит от способа расчёта услуги (руб/м², руб/чел, руб. и т.д.)",
                        max_digits=12,
                        verbose_name="Ставка",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Действует с")),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Действует по"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
                "ordering": ("service", "-valid_from"),
            },
        ),
    ]
