# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем установлен",
            ),
        ),
        migrations.AddField(
            model_name="tariff",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tariffs",
                to="services.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddIndex(
            model_name="tariff",
            index=models.Index(
                fields=["service", "valid_from", "valid_to"],
                name="services_ta_service_b7e53b_idx",
            ),
        ),
    ]
