# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("street", "улица"),
                            ("avenue", "проспект"),
                            ("lane", "переулок"),
                            ("boulevard", "бульвар"),
                            ("square", "площадь"),
                            ("highway", "шоссе"),
                            ("microdistrict", "микрорайон"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
            ],
            options={
                "verbose_name": "Улица",
                "verbose_name_plural": "Улицы",
                "ordering": ("name",),
                "unique_together": {("type", "name")},
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, verbose_name="Номер дома")),
                (
                    "building",
                    models.CharField(
                        blank=True,
                        help_text="Например: корпус 2, строение 1",
                        max_length=10,
                        verbose_name="Корпус/строение",
                    ),
                ),
                (
                    "street",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="houses",
                        to="addresses.street",
                        verbose_name="Улица",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дом",
                "verbose_name_plural": "Дома",
                "ordering": ("street", "number"),
                "unique_together": {("street", "number", "building")},
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, verbose_name="Номер помещения"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("residential", "жилое помещение"),
                            ("non_residential", "нежилое помещение"),
                        ],
                        default="residential",
                        max_length=20,
                        verbose_name="Тип помещения",
                    ),
                ),
                (
                    "area_living",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="S жилая, м²",
                    ),
                ),
                (
                    "area_non_living",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="S нежилая, м²",
                    ),
                ),
                (
                    "area_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="S общая, м²",
                    ),
                ),
                (
                    "area_balcony",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="S балкона/лоджии, м²",
                    ),
                ),
                (
                    "balcony_coefficient",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.30"),
                        help_text="Применяется к S балкона при расчёте начислений (обычно 0.3 или 0.5)",
                        max_digits=3,
                        verbose_name="Коэффициент площади балкона",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="addresses.house",
                        verbose_name="Дом",
                    ),
                ),
            ],
            options={
                "verbose_name": "Помещение",
                "verbose_name_plural": "Помещения",
                "ordering": ("house", "number"),
                "unique_together": {("house", "number")},
            },
        ),
    ]
