# Generated by Django 5.2.17 on 2026-08-27 09:46

from django.db import migrations
from django.db.models import F


def recalculate_area_total_without_balcony(apps, schema_editor):
    """Балкон убран из расчёта площади (по ТЗ) — S общая теперь всегда
    S жилая + S нежилая, без вклада балкона, даже для уже существующих
    помещений, у которых он раньше учитывался."""
    Unit = apps.get_model("addresses", "Unit")
    Unit.objects.update(area_total=F("area_living") + F("area_non_living"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_recalculate_area_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="area_balcony",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="balcony_coefficient",
        ),
        migrations.RunPython(recalculate_area_total_without_balcony, noop_reverse),
    ]
