# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.DateField(verbose_name="Период (первое число месяца)"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Показание",
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False, verbose_name="Внесено вручную нанимателем"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Внесено"),
                ),
            ],
            options={
                "verbose_name": "Показание прибора учёта",
                "verbose_name_plural": "Показания приборов учёта",
                "ordering": ("meter", "-period"),
            },
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=50, verbose_name="Заводской номер"),
                ),
                (
                    "installed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата установки"
                    ),
                ),
                (
                    "verification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата поверки"
                    ),
                ),
                (
                    "next_verification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Следующая поверка"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="В эксплуатации"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="accounts.personalaccount",
                        verbose_name="Лицевой счёт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прибор учёта",
                "verbose_name_plural": "Приборы учёта",
                "ordering": ("account", "service"),
            },
        ),
    ]
