# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meters", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meter",
            name="service",
            field=models.ForeignKey(
                limit_choices_to={"calculation_method": "per_consumption"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meters",
                to="services.service",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="meter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="meters.meter",
                verbose_name="Прибор учёта",
            ),
        ),
    ]
