# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meters", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meterreading",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем внесено",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meter",
            unique_together={("account", "service", "serial_number")},
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(
                fields=["meter", "period"], name="meters_mete_meter_i_30eda9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meterreading",
            unique_together={("meter", "period")},
        ),
    ]
