# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отчество"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "passport_series",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Серия паспорта"
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Номер паспорта"
                    ),
                ),
                (
                    "passport_issued_by",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Кем выдан"
                    ),
                ),
                (
                    "passport_issued_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
            ],
            options={
                "verbose_name": "Наниматель",
                "verbose_name_plural": "Наниматели",
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.CreateModel(
            name="TenantAccountAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True, verbose_name="Основной плательщик"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Например: договор найма №..., смена собственника и т.п.",
                        max_length=255,
                        verbose_name="Основание",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_assignments",
                        to="accounts.personalaccount",
                        verbose_name="Лицевой счёт",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_assignments",
                        to="tenants.tenant",
                        verbose_name="Наниматель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение нанимателя",
                "verbose_name_plural": "История нанимателей по лицевым счетам",
                "ordering": ("-start_date",),
                "indexes": [
                    models.Index(
                        fields=["account", "end_date"],
                        name="tenants_ten_account_992cd1_idx",
                    )
                ],
            },
        ),
    ]
