# Generated by Django 5.2.17 on 2026-08-26 06:40

import apps.receipts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.receipts.models.receipt_upload_path,
                        verbose_name="Файл квитанции",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Сформирована"
                    ),
                ),
                (
                    "emailed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлена по email"
                    ),
                ),
                (
                    "charge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="billing.charge",
                        verbose_name="Начисление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Квитанция",
                "verbose_name_plural": "Квитанции",
                "ordering": ("-generated_at",),
            },
        ),
    ]
