# Generated by Django 5.2.17 on 2026-08-27 09:48

from django.db import migrations, models


def reassign_engineers_to_readonly(apps, schema_editor):
    """Роль «Инженер» убрана из справочника (не используется) — у кого она
    была выставлена, переводим на «Только просмотр», чтобы не остаться с
    невалидным значением роли после удаления choice."""
    User = apps.get_model("users", "User")
    User.objects.filter(role="engineer").update(role="readonly")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(reassign_engineers_to_readonly, noop_reverse),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("accountant", "Бухгалтер"),
                    ("passport_officer", "Паспортист"),
                    ("readonly", "Только просмотр"),
                ],
                default="readonly",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
