# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("update", "Изменение"),
                            ("delete", "Удаление"),
                        ],
                        max_length=10,
                        verbose_name="Действие",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Модель")),
                (
                    "object_id",
                    models.CharField(max_length=50, verbose_name="ID объекта"),
                ),
                (
                    "object_repr",
                    models.CharField(max_length=255, verbose_name="Объект"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Изменения",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата/время"),
                ),
            ],
            options={
                "verbose_name": "Запись аудита",
                "verbose_name_plural": "Журнал аудита",
                "ordering": ("-timestamp",),
            },
        ),
    ]
