# Generated by Django 5.2.17 on 2026-08-26 06:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PenaltySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Основные настройки пени",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Льготный период, дней"
                    ),
                ),
                (
                    "rate_per_day",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.0003"),
                        help_text="Доля от суммы долга, начисляемая за каждый день просрочки (например 1/300 ставки ЦБ)",
                        max_digits=8,
                        verbose_name="Ставка пени в день",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Действующие настройки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки пени",
                "verbose_name_plural": "Настройки пени",
            },
        ),
        migrations.CreateModel(
            name="PenaltyAccrual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculation_date",
                    models.DateField(verbose_name="Дата расчёта пени"),
                ),
                (
                    "days_overdue",
                    models.PositiveIntegerField(verbose_name="Дней просрочки"),
                ),
                (
                    "debt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Сумма долга на дату расчёта",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма пени"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Рассчитано"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalty_accruals",
                        to="accounts.personalaccount",
                        verbose_name="Лицевой счёт",
                    ),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalty_accruals",
                        to="billing.charge",
                        verbose_name="Начисление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Начисление пени",
                "verbose_name_plural": "Начисления пени",
                "ordering": ("-calculation_date",),
                "unique_together": {("charge", "calculation_date")},
            },
        ),
    ]
